import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import { useSignMessage } from 'wagmi'
import WalletConnectProvider from '@walletconnect/web3-provider';


export default function Home() {
	const [, setIsNetworkSwitchHighlighted] =
		useState(false);
	const [, setIsConnectHighlighted] = useState(false);

	const closeAll = () => {
		setIsNetworkSwitchHighlighted(false);
		setIsConnectHighlighted(false);
	};
	const { signMessage } = useSignMessage()
	const handleConnectWallet = async () => {
		const provider = new WalletConnectProvider({
			infuraId: "e417c64f2d2349b3b83de2ae0d49688d",
		});

		try {
			await provider.enable();
			const ethersProvider = new ethers.providers.Web3Provider(provider);
			const signer = ethersProvider.getSigner();
			const address = await signer.getAddress();

			// Fetch the challenge from your backend
			const challengeResponse = await fetch('/auth/web3/generate_challenge', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/x-www-form-urlencoded',
				},
				body: new URLSearchParams({
					client_id: 'your_client_id',
					domain: 'your_domain',
					scope: 'openid email',
					response_type: 'code',
					address: address,
				}),
			});
			const { state, challenge } = await challengeResponse.json();

			// Prompt user to sign the challenge
			const signature = await signer.signMessage(challenge);

			// Submit the signed challenge to your backend
			const submitResponse = await fetch('/auth/web3/submit_challenge', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/x-www-form-urlencoded',
				},
				body: new URLSearchParams({
					client_id: 'your_client_id',
					domain: 'your_domain',
					grant_type: 'authorization_code',
					state: state,
					signature: signature,
				}),
			});
			const submitResult = await submitResponse.json();

			// Handle the response from your backend
			// ...

		} catch (error) {
			console.error('Error:', error);
		} finally {
			await provider.disconnect();
		}
	};


	return (
		<>
			<Head>
				<title>WalletConnect | Next Starter Template</title>
				<meta name="description" content="Generated by create-wc-dapp" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header>
				<div className={styles.header}>
					<div className={styles.logo}>
						<Image src="/logo.svg" alt="WalletConnect Logo" height="32" width="203" />
					</div>
				</div>
			</header>
			<main className={styles.main}>
				<div className={styles.wrapper}>
					<div className={styles.containerCentered}>
						<div onClick={() => signMessage({message: 'hello'})} className={styles.highlight}>
							<w3m-button />
						</div>
						<div onClick={closeAll} className={styles.highlight}>
							<w3m-network-button />
						</div>
					</div>
				</div>
			</main>
			<footer className={styles.footer}>
				<svg
					xmlns="http://www.w3.org/2000/svg"
					fill="none"
					viewBox="0 0 24 24"
					strokeWidth={1.5}
					stroke="currentColor"
					height={16}
					width={16}
				>
				</svg>
				<a
					href="https://docs.walletconnect.com/web3modal/react/about?utm_source=next-starter-template&utm_medium=github&utm_campaign=next-starter-template"
					target="_blank"
					rel="noopener noreferrer"
				>
					Check out the full documentation here
				</a>
			</footer>
		</>
	);
}