apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "trips-web-app.fullname" . }}
  labels:
    {{- include "trips-web-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
    {{- include "trips-web-app.selectorLabels" . | nindent 6 }}
{{ toYaml .Values.podDisruptionBudget | indent 2 }}