version: "2"
linters:
  enable:
    - prealloc
    - revive
    - zerologlint
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  fix: true
formatters:
  enable:
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/DIMO-Network/trips-web-app/api)
        - blank
        - dot
      custom-order: false
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
