ENVIRONMENT: local
PORT: 3007
LOG_LEVEL: info

CLIENT_ID: '0x6dc04b391D38818B2036f80cEf2cF4727e479065'
LOGIN_URL: 'https://login.dimo.org'
DOMAIN: https://localhost:4000/oauth/callback
SCOPE: openid email
RESPONSE_TYPE: code
GRANT_TYPE: authorization_code
AUTH_URL: https://auth.dimo.zone/auth/web3/generate_challenge
SUBMIT_CHALLENGE_URL: https://auth.dimo.zone/auth/web3/submit_challenge
IDENTITY_API_URL: https://identity-api.dimo.zone/query
TOKEN_EXCHANGE_API_URL: https://token-exchange-api.dimo.zone/v1/tokens/exchange
DEVICE_DATA_API_URL: https://device-data-api.dimo.zone/v1
TRIPS_API_BASE_URL: https://trips-api.dimo.zone/v1
PRIVILEGE_NFT_CONTRACT_ADDR: '0xbA5738a18d83D41847dfFbDC6101d37C69c9B0cF'
USERS_API_BASE_URL: https://users-api.dimo.zone/v1
TELEMETRY_API_URL: https://telemetry-api.dimo.zone/query
USE_DEV_CERTS: true


