name: buildpush
on:
  push:
    tags:
      - v*

jobs:
  build_test:
    # The type of runner that the job will run on
    name: buildpush
    runs-on: [self-hosted, linux]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # leaving this here, as ideally we tag the latest image with the git version tag
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: get last image tag
        id: tag
        uses: CumulusDS/get-yaml-paths-action@v0.1.1
        with:
          file: charts/trips-web-app/values.yaml
          buildtag: image.tag

      - name: Update Image Version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@v0.13.2
        with:
          valueFile: 'charts/trips-web-app/values-prod.yaml'
          propertyPath: 'image.tag'
          value: ${{steps.tag.outputs.buildtag}}
          branch: main
          message: 'Update Image Version to ${{steps.tag.outputs.buildtag}}'
